services:
  nginx:
    image: nginx:mainline-alpine-slim
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./docker-data/certbot/conf:/etc/letsencrypt
      - ./docker-data/certbot/www:/var/www/certbot
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    networks:
      - nginx-proxy

  certbot:
    image: certbot/certbot
    volumes:
      - ./docker-data/certbot/conf:/etc/letsencrypt
      - ./docker-data/certbot/lib:/var/lib/letsencrypt
      - ./docker-data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  nginx-proxy:
    name: nginx-proxy

# Initial certbot command
# docker run --rm -it -v ./docker-data/certbot/conf:/etc/letsencrypt -v ./docker-data/certbot/lib:/var/lib/letsencrypt -p 80:80 certbot/certbot certonly --no-eff-email --register-unsafely-without-email --agree-tos --standalone -d example.com
